# Generated by Django 4.0.1 on 2022-02-18 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicetime',
            old_name='start_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='servicetime',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='servicetime',
            name='start_date',
        ),
    ]
