# Generated by Django 4.0.1 on 2022-02-25 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_services', '0003_remove_service_times_service_time_delete_servicetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorderitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_order_items', to='apps_services.service'),
        ),
    ]
