# Generated by Django 4.0.1 on 2022-03-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_services', '0007_alter_team_service_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='service',
        ),
        migrations.AddField(
            model_name='team',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='service_teams', to='apps_services.Service'),
        ),
    ]
